"""
Audit Pipeline — orchestrates the three-agent assessment workflow.

Flow:
    Input → Validate → Auditor (initial draft) → Reviewer (strengthen)
          → Questioning (targeted gaps) → Merge → Final Output
"""

import os

import anthropic
from dotenv import load_dotenv

from agents.auditor import AuditorAgent
from agents.questioning import QuestioningAgent
from agents.reviewer import ReviewerAgent
from utils.logger import get_logger
from utils.validator import validate_input

load_dotenv()

logger = get_logger(__name__)

DEFAULT_MODEL = "claude-opus-4-6"


class AuditPipeline:
    """
    Orchestrates the full multi-agent audit pipeline.

    Agents run sequentially:
      1. AuditorAgent  — initial control assessment
      2. ReviewerAgent — quality review and strengthening
      3. QuestioningAgent — follow-up question generation (conditional)

    The final output merges the reviewer's assessment with follow-up
    questions generated by the questioning agent.
    """

    def __init__(self) -> None:
        api_key = os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise ValueError(
                "ANTHROPIC_API_KEY environment variable is not set. "
                "Please add it to your .env file."
            )

        self.model = os.getenv("MODEL", DEFAULT_MODEL)
        self.client = anthropic.Anthropic(api_key=api_key)

        self.auditor = AuditorAgent(self.client, self.model)
        self.reviewer = ReviewerAgent(self.client, self.model)
        self.questioner = QuestioningAgent(self.client, self.model)

        logger.info(f"AuditPipeline initialised — model: {self.model}")

    def run(self, input_data: dict) -> dict:
        """
        Execute the full audit pipeline for a given input.

        Args:
            input_data: Dictionary with 'control', 'requirement', 'evidence' keys.

        Returns:
            Final structured audit output dictionary.

        Raises:
            ValueError: On input validation failure.
            anthropic.APIError: On API communication failures.
        """
        # Step 0: Validate input
        audit_input, error = validate_input(input_data)
        if error:
            raise ValueError(error)

        logger.info(
            f"Pipeline — starting for control: {audit_input.control[:60]}..."
        )

        # Step 1: Initial assessment
        auditor_output = self.auditor.assess(audit_input)
        logger.info("Pipeline — Step 1/3 complete (Auditor)")

        # Step 2: Review and strengthen
        reviewed_output = self.reviewer.review(audit_input, auditor_output)
        logger.info("Pipeline — Step 2/3 complete (Reviewer)")

        # Step 3: Generate follow-up questions (conditional)
        follow_up_questions = self.questioner.generate_questions(
            audit_input, reviewed_output
        )
        logger.info(
            f"Pipeline — Step 3/3 complete (Questioning): "
            f"{len(follow_up_questions)} question(s)"
        )

        # Merge follow-up questions into the final output
        reviewed_output["follow_up_questions"] = follow_up_questions

        logger.info("Pipeline — audit complete")
        return reviewed_output
